#!/bin/sh
# Этот скрипт автоматически обновляет файл /etc/hosts на роутере OpenWrt
# === START: [2026-09-22] Поддержка Dual-Stack (IPv4 + IPv6) ===
# Использование: sh update_router_hosts.sh [VPS_IPv4] [VPS_IPv6]

VPS_IP="$1"
VPS_IPV6="$2"

if [ -z "$VPS_IP" ]; then
    # Если IPv4 не передан (например, при запуске из крона), читаем из файла
    if [ -f /etc/sni_proxy_ip ]; then
        VPS_IP=$(cat /etc/sni_proxy_ip)
    else
        echo "Ошибка: не указан IPv4 адрес VPS."
        echo "Использование: $0 <VPS_IPv4> [VPS_IPv6]"
        exit 1
    fi
else
    # Сохраняем IPv4 для будущих запусков через cron
    echo "$VPS_IP" > /etc/sni_proxy_ip
fi

if [ -n "$VPS_IPV6" ]; then
    if [ "$VPS_IPV6" = "none" ] || [ "$VPS_IPV6" = "off" ]; then
        rm -f /etc/sni_proxy_ipv6
        VPS_IPV6=""
    else
        echo "$VPS_IPV6" > /etc/sni_proxy_ipv6
    fi
elif [ -f /etc/sni_proxy_ipv6 ]; then
    VPS_IPV6=$(cat /etc/sni_proxy_ipv6)
fi
# === END: [2026-09-22] Поддержка Dual-Stack (IPv4 + IPv6) ===

TEMPLATE_URL="https://raw.githubusercontent.com/uraz0v/sni-proxy/main/mega_hosts_template.txt"
TMP_TEMPLATE="/tmp/mega_hosts_template.txt"
TMP_NEW="/tmp/hosts_new.txt"
MARKER="# --- SNI PROXY AUTOGENERATED ---"

# === START: [2026-09-22] Надежная загрузка шаблона через curl с таймаутом и IPv6 fallback ===
echo "Скачиваем свежий шаблон с GitHub..."
CURL_RESOLVE=""
if [ -n "$VPS_IPV6" ]; then
    CURL_RESOLVE="--resolve raw.githubusercontent.com:443:[$VPS_IPV6]"
fi

if ! curl -sL --connect-timeout 10 $CURL_RESOLVE -o "$TMP_TEMPLATE" "$TEMPLATE_URL"; then
    if ! wget -q -T 10 -O "$TMP_TEMPLATE" "$TEMPLATE_URL"; then
        echo "Ошибка скачивания файла!"
        exit 1
    fi
fi
# === END: [2026-09-22] Надежная загрузка шаблона через curl с таймаутом и IPv6 fallback ===

if [ ! -s "$TMP_TEMPLATE" ]; then
    echo "Ошибка: скачанный файл пуст."
    exit 1
fi

# === START: [2026-09-22] Поддержка Dual-Stack (IPv4 + IPv6) ===
if [ -n "$VPS_IPV6" ]; then
    echo "Подставляем IP сервера (Dual-Stack: IPv4 $VPS_IP, IPv6 $VPS_IPV6)..."
else
    echo "Подставляем IP сервера (IPv4 $VPS_IP)..."
fi

awk -v ip4="$VPS_IP" -v ip6="$VPS_IPV6" '{
    if ($1 == "YOUR_VPS_IP") {
        print ip4 " " $2
        if (ip6 != "") print ip6 " " $2
    } else {
        print $0
    }
}' "$TMP_TEMPLATE" > /tmp/proxy_block.txt
# === END: [2026-09-22] Поддержка Dual-Stack (IPv4 + IPv6) ===

echo "Анализируем текущий /etc/hosts..."
# Извлекаем все строки до нашего маркера (это оригинальные системные записи роутера)
awk -v marker="$MARKER" '{
    if ($0 == marker) exit
    print $0
}' /etc/hosts > /tmp/hosts_base.txt

# Собираем новый файл
cat /tmp/hosts_base.txt > "$TMP_NEW"
echo "$MARKER" >> "$TMP_NEW"
cat /tmp/proxy_block.txt >> "$TMP_NEW"

# Сравниваем новый файл со старым
if cmp -s /etc/hosts "$TMP_NEW"; then
    echo "Обновлений нет. Файл hosts актуален."
    rm "$TMP_TEMPLATE" /tmp/proxy_block.txt "$TMP_NEW" /tmp/hosts_base.txt
else
    echo "Обнаружены изменения! Обновляем /etc/hosts..."
    
    # Делаем бекап по правилам пользователя (одна копия за день)
    CURRENT_DATE=$(date +%Y-%m-%d)
    BACKUP_FILE="/etc/hosts_${CURRENT_DATE}"
    
    if [ ! -f "$BACKUP_FILE" ]; then
        cp /etc/hosts "$BACKUP_FILE"
    fi
    
    # Очищаем место: удаляем ВСЕ остальные бекапы hosts, кроме сегодняшнего
    for f in /etc/hosts_20*; do
        if [ "$f" != "$BACKUP_FILE" ] && [ -f "$f" ]; then
            rm -f "$f"
        fi
    done
    # Удаляем старые форматы бекапов, если они были
    rm -f /etc/hosts.bak.*
    
    mv "$TMP_NEW" /etc/hosts
    echo "Перезапускаем dnsmasq..."
    /etc/init.d/dnsmasq restart
fi

# Устанавливаем задачу в cron, если её еще нет
if ! grep -q "update_router_hosts.sh" /etc/crontabs/root 2>/dev/null; then
    echo "Устанавливаем автообновление в cron (каждый день в 05:00)..."
    echo "0 5 * * * /bin/sh /etc/update_router_hosts.sh 2>&1 | logger -t sni-proxy" >> /etc/crontabs/root
    /etc/init.d/cron restart
fi

echo "✅ Готово!"
