#!/bin/sh
# Этот скрипт автоматически обновляет файл /etc/hosts на роутере OpenWrt
# Использование: sh update_router_hosts.sh [VPS_IP]

VPS_IP="$1"
if [ -z "$VPS_IP" ]; then
    # Если IP не передан (например, при запуске из крона), пытаемся прочитать из файла
    if [ -f /etc/sni_proxy_ip ]; then
        VPS_IP=$(cat /etc/sni_proxy_ip)
    else
        echo "Ошибка: не указан IP адрес VPS."
        echo "Использование: $0 <VPS_IP>"
        exit 1
    fi
else
    # Сохраняем IP для будущих запусков через cron
    echo "$VPS_IP" > /etc/sni_proxy_ip
fi

TEMPLATE_URL="https://raw.githubusercontent.com/uraz0v/sni-proxy/main/mega_hosts_template.txt"
TMP_TEMPLATE="/tmp/mega_hosts_template.txt"
TMP_NEW="/tmp/hosts_new.txt"
MARKER="# --- SNI PROXY AUTOGENERATED ---"

echo "Скачиваем свежий шаблон с GitHub..."
if ! wget -qO "$TMP_TEMPLATE" "$TEMPLATE_URL"; then
    if ! curl -sL -o "$TMP_TEMPLATE" "$TEMPLATE_URL"; then
        echo "Ошибка скачивания файла!"
        exit 1
    fi
fi

if [ ! -s "$TMP_TEMPLATE" ]; then
    echo "Ошибка: скачанный файл пуст."
    exit 1
fi

echo "Подставляем IP сервера ($VPS_IP)..."
sed "s/YOUR_VPS_IP/$VPS_IP/g" "$TMP_TEMPLATE" > /tmp/proxy_block.txt

echo "Анализируем текущий /etc/hosts..."
# Извлекаем все строки до нашего маркера (это оригинальные системные записи роутера)
awk -v marker="$MARKER" '{
    if ($0 == marker) exit
    print $0
}' /etc/hosts > /tmp/hosts_base.txt

# Собираем новый файл
cat /tmp/hosts_base.txt > "$TMP_NEW"
echo "$MARKER" >> "$TMP_NEW"
cat /tmp/proxy_block.txt >> "$TMP_NEW"

# Сравниваем новый файл со старым
if cmp -s /etc/hosts "$TMP_NEW"; then
    echo "Обновлений нет. Файл hosts актуален."
    rm "$TMP_TEMPLATE" /tmp/proxy_block.txt "$TMP_NEW" /tmp/hosts_base.txt
else
    echo "Обнаружены изменения! Обновляем /etc/hosts..."
    
    # Делаем бекап по правилам пользователя (одна копия за день)
    CURRENT_DATE=$(date +%Y-%m-%d)
    BACKUP_FILE="/etc/hosts_${CURRENT_DATE}"
    
    if [ ! -f "$BACKUP_FILE" ]; then
        cp /etc/hosts "$BACKUP_FILE"
    fi
    
    # Очищаем место: удаляем ВСЕ остальные бекапы hosts, кроме сегодняшнего
    for f in /etc/hosts_20*; do
        if [ "$f" != "$BACKUP_FILE" ] && [ -f "$f" ]; then
            rm -f "$f"
        fi
    done
    # Удаляем старые форматы бекапов, если они были
    rm -f /etc/hosts.bak.*
    
    mv "$TMP_NEW" /etc/hosts
    echo "Перезапускаем dnsmasq..."
    /etc/init.d/dnsmasq restart
fi

# Устанавливаем задачу в cron, если её еще нет
if ! grep -q "update_router_hosts.sh" /etc/crontabs/root 2>/dev/null; then
    echo "Устанавливаем автообновление в cron (каждый день в 05:00)..."
    echo "0 5 * * * /bin/sh /etc/update_router_hosts.sh 2>&1 | logger -t sni-proxy" >> /etc/crontabs/root
    /etc/init.d/cron restart
fi

echo "✅ Готово!"
