name: Auto Update Lists
on:
  schedule:
    - cron: '0 3 * * *' # Каждую ночь в 03:00
  workflow_dispatch: # Позволяет запускать обновление вручную из интерфейса GitHub

jobs:
  update-lists:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Разрешаем боту делать коммиты
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Domain Lists and Hosts Template
        run: |
          bash generate.sh

          
      - name: Check for changes and commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add lists/ mega_hosts_template.txt
          
          if git diff-index --quiet HEAD; then
            echo "No changes in lists. Skipping commit."
          else
            echo "Changes detected. Committing and pushing."
            git commit -m "chore: auto-update domains and hosts template"
            git push
          fi
